
import { Decks } from './types';

export const CATEGORY_LABELS: Record<string, string> = {
  alphabet: "Unit 1: The Alphabet",
  basics: "Unit 2: Greetings & Basics",
  numbers: "Unit 3: Numbers & Time",
  family: "Unit 4: People & Family",
  colors: "Unit 5: Colors & Describe",
  food: "Unit 6: Food & Grocery Survival",
  places: "Unit 7: City & Home",
  verbs: "Unit 8: Action Verbs",
  questions: "Unit 9: Question Words",
  emergency: "Unit 10: Emergency",
  custom: "📂 AI Generated / Custom"
};

export const INITIAL_DECKS: Decks = {
  alphabet: [
    { f: "А а", t: "a", p: "ah", c: "Sound: Father" }, { f: "Б б", t: "b", p: "beh", c: "Sound: Bat" },
    { f: "В в", t: "v", p: "veh", c: "Sound: Vet" }, { f: "Г г", t: "g", p: "geh", c: "Sound: Go" },
    { f: "Д д", t: "d", p: "deh", c: "Sound: Dog" }, { f: "Е е", t: "ye", p: "yeh", c: "Sound: Yes" },
    { f: "Ё ё", t: "yo", p: "yo", c: "Sound: Yonder" }, { f: "Ж ж", t: "zh", p: "zheh", c: "Sound: Pleasure" },
    { f: "З з", t: "z", p: "zeh", c: "Sound: Zoo" }, { f: "И и", t: "ee", p: "ee", c: "Sound: See" },
    { f: "Й й", t: "y", p: "ee-short", c: "Sound: Boy" }, { f: "К к", t: "k", p: "kah", c: "Sound: Kit" },
    { f: "Л л", t: "l", p: "el", c: "Sound: Lamp" }, { f: "М м", t: "m", p: "em", c: "Sound: Map" },
    { f: "Н н", t: "n", p: "en", c: "Sound: No" }, { f: "О о", t: "o", p: "oh", c: "Sound: More" },
    { f: "П п", t: "p", p: "peh", c: "Sound: Pot" }, { f: "Р р", t: "r", p: "err", c: "Rolled R" },
    { f: "С с", t: "s", p: "ess", c: "Sound: Snake" }, { f: "Т т", t: "t", p: "teh", c: "Sound: Top" },
    { f: "У у", t: "oo", p: "oo", c: "Sound: Moon" }, { f: "Ф ф", t: "f", p: "eff", c: "Sound: Face" },
    { f: "Х х", t: "h", p: "kha", c: "Sound: Loch" }, { f: "Ц ц", t: "ts", p: "tseh", c: "Sound: Sits" },
    { f: "Ч ч", t: "ch", p: "cheh", c: "Sound: Chips" }, { f: "Ш ш", t: "sh", p: "shah", c: "Sound: Shoe" },
    { f: "Щ щ", t: "shch", p: "shcha", c: "Sound: Fresh cheese" }, { f: "Ъ", t: "Hard Sign", p: "Silent", c: "Adds a pause" },
    { f: "Ы", t: "ih", p: "yery", c: "Deep guttural I" }, { f: "Ь", t: "Soft Sign", p: "Silent", c: "Softens letter" },
    { f: "Э э", t: "eh", p: "eh", c: "Sound: Met" }, { f: "Ю ю", t: "yu", p: "yoo", c: "Sound: Universe" },
    { f: "Я я", t: "ya", p: "ya", c: "Sound: Yacht" }
  ],
  basics: [
    { f: "Привет", t: "Hi", p: "Privet", c: "Informal greeting" },
    { f: "Здравствуйте", t: "Hello", p: "Zdrav-stvuy-te", c: "Formal greeting" },
    { f: "Как дела?", t: "How are you?", p: "Kak dela?", c: "Friendly inquiry" },
    { f: "Хорошо", t: "Good / Well", p: "Horosho", c: "Common response" },
    { f: "Плохо", t: "Bad", p: "Plokho", c: "Negative response" },
    { f: "Меня зовут...", t: "My name is...", p: "Menya zovut", c: "Introductions" },
    { f: "Очень приятно", t: "Nice to meet you", p: "Ochen' priyatno", c: "Formal/Polite" },
    { f: "Пожалуйста", t: "Please / You're welcome", p: "Pozhaluysta", c: "Dual meaning" },
    { f: "Спасибо", t: "Thank you", p: "Spasibo", c: "Polite gratitude" },
    { f: "Извините", t: "Excuse me", p: "Izvinite", c: "Asking for attention" },
    { f: "Простите", t: "Sorry", p: "Prostite", c: "Apologizing" },
    { f: "Вы говорите по-английски?", t: "Do you speak English?", p: "Vy govorite po-angliyski?", c: "Survival phrase" },
    { f: "Я не понимаю", t: "I don't understand", p: "Ya ne ponimayu", c: "Essential phrase" },
    { f: "Повторите, пожалуйста", t: "Repeat, please", p: "Povtorite, pozhaluysta", c: "Learning aid" },
    { f: "Медленнее", t: "Slower", p: "Medlenneye", c: "Requesting speed change" },
    { f: "Да", t: "Yes", p: "Da", c: "Agreement" },
    { f: "Нет", t: "No", p: "Net", c: "Disagreement" },
    { f: "Конечно", t: "Of course", p: "Konechno", c: "Strong agreement" },
    { f: "Может быть", t: "Maybe", p: "Mozhet byt'", c: "Uncertainty" },
    { f: "До свидания", t: "Goodbye", p: "Do svidaniya", c: "Formal exit" },
    { f: "Пока", t: "Bye", p: "Poka", c: "Informal exit" },
    { f: "Удачи!", t: "Good luck!", p: "Udachi!", c: "Wishing well" }
  ],
  numbers: [
    { f: "Один", t: "1", p: "Odin", c: "One" },
    { f: "Два", t: "2", p: "Dva", c: "Two" },
    { f: "Три", t: "3", p: "Tri", c: "Three" },
    { f: "Четыре", t: "4", p: "Chetyre", c: "Four" },
    { f: "Пять", t: "5", p: "Pyat'", c: "Five" },
    { f: "Шесть", t: "6", p: "Shest'", c: "Six" },
    { f: "Семь", t: "7", p: "Sem'", c: "Seven" },
    { f: "Восемь", t: "8", p: "Vosem'", c: "Eight" },
    { f: "Девять", t: "9", p: "Devyat'", c: "Nine" },
    { f: "Десять", t: "10", p: "Desyat'", c: "Ten" },
    { f: "Одиннадцать", t: "11", p: "Odinnadtsat'", c: "Eleven" },
    { f: "Двенадцать", t: "12", p: "Dvenadtsat'", c: "Twelve" },
    { f: "Двадцать", t: "20", p: "Dvadtsat'", c: "Twenty" },
    { f: "Тридцать", t: "30", p: "Tridtsat'", c: "Thirty" },
    { f: "Сорок", t: "40", p: "Sorok", c: "Forty" },
    { f: "Пятьдесят", t: "50", p: "Pyat'desyat", c: "Fifty" },
    { f: "Сто", t: "100", p: "Sto", c: "One hundred" },
    { f: "Двести", t: "200", p: "Dvesti", c: "Two hundred" },
    { f: "Пятьсот", t: "500", p: "Pyat'sot", c: "Five hundred" },
    { f: "Тысяча", t: "1000", p: "Tysyacha", c: "One thousand" },
    { f: "Первый", t: "First", p: "Perviy", c: "Ordinal" },
    { f: "Второй", t: "Second", p: "Vtoroy", c: "Ordinal" },
    { f: "Третий", t: "Third", p: "Tretiy", c: "Ordinal" }
  ],
  family: [
    { f: "Семья", t: "Family", p: "Sem'ya", c: "The whole group" },
    { f: "Мама", t: "Mother / Mom", p: "Mama", c: "Parent" },
    { f: "Папа", t: "Father / Dad", p: "Papa", c: "Parent" },
    { f: "Родители", t: "Parents", p: "Roditeli", c: "Group" },
    { f: "Сын", t: "Son", p: "Syn", c: "Male child" },
    { f: "Дочь", t: "Daughter", p: "Doch'", c: "Female child" },
    { f: "Брат", t: "Brother", p: "Brat", c: "Male sibling" },
    { f: "Сестра", t: "Sister", p: "Sestra", c: "Female sibling" },
    { f: "Бабушка", t: "Grandmother", p: "Babushka", c: "Our hero!" },
    { f: "Дедушка", t: "Grandfather", p: "Dedushka", c: "Male grandparent" },
    { f: "Дядя", t: "Uncle", p: "Dyadya", c: "Relative" },
    { f: "Тётя", t: "Aunt", p: "Tyotya", c: "Relative" },
    { f: "Муж", t: "Husband", p: "Muzh", c: "Spouse" },
    { f: "Жена", t: "Wife", p: "Zhena", c: "Spouse" },
    { f: "Ребёнок", t: "Child", p: "Rebyonok", c: "Single kid" },
    { f: "Дети", t: "Children", p: "Deti", c: "Plural kids" },
    { f: "Друг", t: "Friend (M)", p: "Drug", c: "Companion" },
    { f: "Подруга", t: "Friend (F)", p: "Podruga", c: "Companion" }
  ],
  colors: [
    { f: "Цвет", t: "Color", p: "Tsvet", c: "Category" },
    { f: "Красный", t: "Red", p: "Krasniy", c: "Bold primary" },
    { f: "Синий", t: "Blue (Dark)", p: "Siniy", c: "Standard blue" },
    { f: "Голубой", t: "Light Blue", p: "Goluboy", c: "Sky blue" },
    { f: "Зелёный", t: "Green", p: "Zelyoniy", c: "Nature" },
    { f: "Жёлтый", t: "Yellow", p: "Zhyoltiy", c: "Sun" },
    { f: "Чёрный", t: "Black", p: "Chorniy", c: "Darkest" },
    { f: "Белый", t: "White", p: "Beliy", c: "Snow" },
    { f: "Серый", t: "Grey", p: "Seriy", c: "Neutral" },
    { f: "Коричневый", t: "Brown", p: "Korichneviy", c: "Earth" },
    { f: "Оранжевый", t: "Orange", p: "Oranzheviy", c: "Bright" },
    { f: "Фиолетовый", t: "Purple", p: "Fioletoviy", c: "Royal" },
    { f: "Розовый", t: "Pink", p: "Rozoviy", c: "Soft red" },
    { f: "Золотой", t: "Gold", p: "Zolotoy", c: "Metallic" },
    { f: "Серебряный", t: "Silver", p: "Serebryaniy", c: "Metallic" }
  ],
  food: [
    { f: "Еда", t: "Food", p: "Yeda", c: "Nourishment" },
    { f: "Завтрак", t: "Breakfast", p: "Zavtrak", c: "Morning meal" },
    { f: "Обед", t: "Lunch", p: "Obed", c: "Midday meal" },
    { f: "Ужин", t: "Dinner", p: "Uzhin", c: "Evening meal" },
    { f: "Хлеб", t: "Bread", p: "Khleb", c: "Daily staple" },
    { f: "Вода", t: "Water", p: "Voda", c: "Hydration" },
    { f: "Чай", t: "Tea", p: "Chay", c: "Cultural favorite" },
    { f: "Кофе", t: "Coffee", p: "Kofe", c: "Caffeine" },
    { f: "Молоко", t: "Milk", p: "Moloko", c: "Dairy" },
    { f: "Мясо", t: "Meat", p: "Myaso", c: "Protein" },
    { f: "Рыба", t: "Fish", p: "Ryba", c: "Seafood" },
    { f: "Курица", t: "Chicken", p: "Kuritsa", c: "Poultry" },
    { f: "Овощи", t: "Vegetables", p: "Ovoshchi", c: "Greens" },
    { f: "Фрукты", t: "Fruits", p: "Frukty", c: "Sweet" },
    { f: "Яблоко", t: "Apple", p: "Yabloko", c: "Common fruit" },
    { f: "Картофель", t: "Potato", p: "Kartofel'", c: "Russian staple" },
    { f: "Борщ", t: "Borscht", p: "Borshch", c: "Beet soup" },
    { f: "Пельмени", t: "Pelmeni", p: "Pel'meni", c: "Dumplings" },
    { f: "Сметана", t: "Sour Cream", p: "Smetana", c: "Essential garnish" },
    { f: "Сахар", t: "Sugar", p: "Sakhar", c: "Sweetener" },
    { f: "Соль", t: "Salt", p: "Sol'", c: "Seasoning" },
    { f: "Вкусно", t: "Tasty / Delicious", p: "Vkusno", c: "Compliment" },
    { f: "Я хочу есть", t: "I'm hungry", p: "Ya hochu yest'", c: "Urgent state" },
    { f: "Счёт, пожалуйста", t: "Bill, please", p: "Schyot, pozhaluysta", c: "Restaurant" }
  ],
  places: [
    { f: "Где...?", t: "Where is...?", p: "Gde...?", c: "Locating" },
    { f: "Город", t: "City", p: "Gorod", c: "Urban" },
    { f: "Центр", t: "Center", p: "Tsentr", c: "Downtown" },
    { f: "Улица", t: "Street", p: "Ulitsa", c: "Address" },
    { f: "Дом", t: "House", p: "Dom", c: "Residence" },
    { f: "Магазин", t: "Store", p: "Magazin", c: "Shopping" },
    { f: "Рынок", t: "Market", p: "Rynok", c: "Traditional shopping" },
    { f: "Аптека", t: "Pharmacy", p: "Apteka", c: "Medicine" },
    { f: "Больница", t: "Hospital", p: "Bol'nitsa", c: "Medical" },
    { f: "Метро", t: "Metro / Subway", p: "Metro", c: "Transport" },
    { f: "Вокзал", t: "Train Station", p: "Vokzal", c: "Long distance" },
    { f: "Аэропорт", t: "Airport", p: "Aeroport", c: "Travel" },
    { f: "Остановка", t: "Bus Stop", p: "Ostanovka", c: "Local transport" },
    { f: "Гостиница", t: "Hotel", p: "Gostinitsa", c: "Stay" },
    { f: "Ресторан", t: "Restaurant", p: "Restoran", c: "Dining" },
    { f: "Туалет", t: "Toilet", p: "Tualet", c: "Restroom" },
    { f: "Музей", t: "Museum", p: "Muzey", c: "Culture" },
    { f: "Парк", t: "Park", p: "Park", c: "Outdoors" },
    { f: "Банк", t: "Bank", p: "Bank", c: "Finance" },
    { f: "Почта", t: "Post Office", p: "Pochta", c: "Letters" },
    { f: "Налево", t: "To the left", p: "Nalevo", c: "Direction" },
    { f: "Направо", t: "To the right", p: "Napravo", c: "Direction" },
    { f: "Прямо", t: "Straight", p: "Pryamo", c: "Direction" }
  ],
  verbs: [
    { f: "Быть", t: "To be", p: "Byt'", c: "Base verb" },
    { f: "Идти", t: "To go (on foot)", p: "Idti", c: "Movement" },
    { f: "Ехать", t: "To go (by vehicle)", p: "Yekhat'", c: "Movement" },
    { f: "Делать", t: "To do / To make", p: "Delat'", c: "Action" },
    { f: "Знать", t: "To know", p: "Znat'", c: "Knowledge" },
    { f: "Понимать", t: "To understand", p: "Ponimat'", c: "Comprehension" },
    { f: "Говорить", t: "To speak / To say", p: "Govorit'", c: "Speech" },
    { f: "Читать", t: "To read", p: "Chitat'", c: "Input" },
    { f: "Писать", t: "To write", p: "Pisat'", c: "Output" },
    { f: "Слушать", t: "To listen", p: "Slushat'", c: "Input" },
    { f: "Смотреть", t: "To watch / To look", p: "Smotret'", c: "Sight" },
    { f: "Хотеть", t: "To want", p: "Khotet'", c: "Desire" },
    { f: "Мочь", t: "To be able to", p: "Moch'", c: "Ability" },
    { f: "Любить", t: "To love / To like", p: "Lyubit'", c: "Emotion" },
    { f: "Работать", t: "To work", p: "Rabotat'", c: "Labor" },
    { f: "Жить", t: "To live", p: "Zhit'", c: "Existence" },
    { f: "Покупать", t: "To buy", p: "Pokupat'", c: "Commerce" },
    { f: "Есть", t: "To eat", p: "Yest'", c: "Nourishment" },
    { f: "Пить", t: "To drink", p: "Pit'", c: "Nourishment" },
    { f: "Спать", t: "To sleep", p: "Spat'", c: "Rest" },
    { f: "Думать", t: "To think", p: "Dumat'", c: "Cognition" }
  ],
  questions: [
    { f: "Кто?", t: "Who?", p: "Kto?", c: "Identify person" },
    { f: "Что?", t: "What?", p: "Chto?", c: "Identify thing" },
    { f: "Когда?", t: "When?", p: "Kogda?", c: "Identify time" },
    { f: "Где?", t: "Where?", p: "Gde?", c: "Identify location" },
    { f: "Куда?", t: "Where to?", p: "Kuda?", c: "Identify destination" },
    { f: "Откуда?", t: "Where from?", p: "Otkuda?", c: "Identify origin" },
    { f: "Почему?", t: "Why?", p: "Pochemu?", c: "Identify reason" },
    { f: "Зачем?", t: "What for?", p: "Zachem?", c: "Identify purpose" },
    { f: "Как?", t: "How?", p: "Kak?", c: "Identify manner" },
    { f: "Сколько?", t: "How much / How many?", p: "Skol'ko?", c: "Identify quantity" },
    { f: "Чей?", t: "Whose?", p: "Chey?", c: "Identify ownership" },
    { f: "Какой?", t: "Which / What kind of?", p: "Kakoy?", c: "Identify quality" },
    { f: "Который час?", t: "What time is it?", p: "Kotory chas?", c: "Clock check" }
  ],
  emergency: [
    { f: "Помогите!", t: "Help!", p: "Pomogite!", c: "General emergency" },
    { f: "Вызовите полицию!", t: "Call the police!", p: "Vyzovite politsiyu!", c: "Legal emergency" },
    { f: "Вызовите скорую!", t: "Call an ambulance!", p: "Vyzovite skoruyu!", c: "Medical emergency" },
    { f: "Пожар!", t: "Fire!", p: "Pozhar!", c: "Danger" },
    { f: "Я потерялся", t: "I'm lost (M)", p: "Ya poteryalsya", c: "Location issue" },
    { f: "Я потерялась", t: "I'm lost (F)", p: "Ya poteryalas'", c: "Location issue" },
    { f: "Меня обокрали", t: "I've been robbed", p: "Menya obokrali", c: "Crime" },
    { f: "Где ближайшая больница?", t: "Where's the nearest hospital?", p: "Gde blizhayshaya bol'nitsa?", c: "Medical" },
    { f: "Мне плохо", t: "I feel sick", p: "Mne ploho", c: "Health" },
    { f: "У меня болит...", t: "My ... hurts", p: "U menya bolit...", c: "Pain" },
    { f: "Остановитесь!", t: "Stop!", p: "Ostanovites'!", c: "Command" },
    { f: "Осторожно!", t: "Watch out!", p: "Ostorozhno!", c: "Warning" },
    { f: "Это срочно!", t: "It's urgent!", p: "Eto srochno!", c: "Priority" }
  ]
};
